# Generated by Django 5.1.6 on 2025-03-04 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('basemodal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='johukumapp.basemodal')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Service_Provider', 'Service_Provider'), ('User', 'User')], max_length=50)),
                ('referral_code', models.CharField(blank=True, max_length=8, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('unique_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('range_field', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('johukumapp.basemodal', models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('basemodal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='johukumapp.basemodal')),
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(max_length=250, upload_to='service_images/')),
                ('service_name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
            bases=('johukumapp.basemodal',),
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('basemodal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='johukumapp.basemodal')),
                ('booking_id', models.CharField(max_length=6, unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('booking_summary', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_id', models.ManyToManyField(blank=True, null=True, to='johukumapp.service')),
            ],
            bases=('johukumapp.basemodal',),
        ),
        migrations.CreateModel(
            name='ConfirmBooking',
            fields=[
                ('basemodal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='johukumapp.basemodal')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_view', models.BooleanField(default=False)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='johukumapp.bookingslot')),
                ('service_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_id', models.ManyToManyField(blank=True, null=True, to='johukumapp.service')),
            ],
            bases=('johukumapp.basemodal',),
        ),
        migrations.AddField(
            model_name='user',
            name='service_id',
            field=models.ManyToManyField(blank=True, null=True, to='johukumapp.service'),
        ),
    ]
